export const featured = [
  { chip: "Healthcare · Flagship", cls: "g", flag: true,
    title: "PriceScope — Hospital Price Transparency Intelligence",
    body: "CMS forces hospitals to publish negotiated rates in files that are famously public-but-unusable. PriceScope parses the three real format dialects, quarantines bad rows, and maps dirty charge descriptions with a measured LLM-assisted pipeline.",
    metric: "93.75% description-mapping accuracy · 2.64× Medicare median · planted outlier recovered as top exposure",
    tags: ["DuckDB", "Python", "Claude API", "Evidence.dev", "8 tests"],
    repo: "hospital-price-intelligence" },
  { chip: "Experimentation", cls: "v",
    title: "expkit — A/B Testing & Experimentation Framework",
    body: "Frequentist + Bayesian + always-valid sequential inference, built around the three ways experiments actually fail: peeking, novelty effects, and Simpson's paradox — each planted in simulated data and caught.",
    metric: "Naive daily peeking: 24% false positives · mSPRT always-valid: 1.2% · 38 tests",
    tags: ["Python", "scipy", "statsmodels", "Streamlit"],
    repo: "ab-testing-framework" },
  { chip: "Causal Inference", cls: "v",
    title: "Causal Inference Casebook",
    body: "When you can't run the experiment: DiD, synthetic control, and propensity stratification — each case computes the naive answer first, shows it wrong, recovers the planted truth, and tests its own assumption.",
    metric: "Naive +44 vs truth +8 → DiD recovers 7.97 ± 0.35 · placebo tests null",
    tags: ["Python", "statsmodels", "scipy", "9 tests"],
    repo: "causal-inference-casebook" },
  { chip: "Product Analytics", cls: "p",
    title: "GrowthLedger — Growth Accounting & Retention",
    body: "The analytics vocabulary of growth teams, done with rigor: MAU decomposition with quick ratio, SQL cohort triangles, aha-moment activation analysis, and the L28 power-user curve on a 421k-event log.",
    metric: "Activated users: 45.3% week-4 retention vs 18.2% — recovered by SQL, pinned by tests",
    tags: ["SQL", "DuckDB", "Python", "6 tests"],
    repo: "product-growth-analytics" },
  { chip: "AI Engineering", cls: "",
    title: "Analytics RAG Agent — Chat With the Data Platform",
    body: "Routes questions between documentation retrieval (with cited sources) and guarded text-to-SQL. Guardrails enforced outside the model: statement validation, table allowlists, read-only execution.",
    metric: "Routing 14/14 · retrieval hit@4 8/8 · SQL guard suite green · 33 tests",
    tags: ["LangChain", "Chroma", "Claude API", "DuckDB"],
    repo: "analytics-rag-agent" },
  { chip: "AI Operations", cls: "",
    title: "TokenLedger — LLM Cost & Quality Analytics",
    body: "Analytics on AI systems: every LLM call traced to OpenTelemetry GenAI conventions, warehoused, and read out as cost-per-successful-answer, prompt-version economics, and failure-aware anomaly detection.",
    metric: "v2 prompt +6.5pp quality at 1.35× cost · retry storm caught at failure z=5.3",
    tags: ["Python", "DuckDB", "OpenTelemetry", "9 tests"],
    repo: "llm-ops-analytics" },
];

export const projects = [
  { c: "health", pc: "gold", cat: "Healthcare · Policy · AI", tests: "8 tests", title: "PriceScope — Price Transparency Intelligence",
    body: "Hospital MRFs — public but famously unusable — parsed across 3 real dialects into payer-negotiation intelligence with an LLM-assisted description mapper.",
    m: "93.75% mapping accuracy · 2.64× Medicare median · $6.8M modeled exposure found", repo: "hospital-price-intelligence" },
  { c: "health", cat: "Healthcare · Spark", tests: "12 tests", title: "Claims Medallion Pipeline",
    body: "PySpark + Delta Lake in the CMS DE-SynPUF schema: bronze → silver with reasoned quarantine → gold clinical analytics (PMPM, readmissions, high-cost members).",
    m: "2,889 claims → 98/98 planted defects quarantined · zero silent drops · 20.9% readmission rate", repo: "healthcare-claims-pipeline" },
  { c: "stats", pc: "v", cat: "Experimentation", tests: "38 tests", title: "A/B Testing & Experimentation Framework",
    body: "Power analysis, frequentist + Bayesian engines, always-valid sequential inference, SRM gates — with peeking, novelty, and Simpson's paradox planted and caught.",
    m: "Peeking inflates false positives to 24% vs 1.2% under mSPRT — measured on 500 A/A simulations", repo: "ab-testing-framework" },
  { c: "stats", pc: "v", cat: "Causal Inference", tests: "9 tests", title: "Causal Inference Casebook",
    body: "DiD, synthetic control, and propensity stratification — the naive answer computed first and shown wrong before the method recovers planted truth.",
    m: "Naive +44 vs truth +8 → DiD 7.97±0.35 · synthetic control ATT −9.1 · matching debiases 2.7×", repo: "causal-inference-casebook" },
  { c: "stats", pc: "p", cat: "Product Analytics", tests: "6 tests", title: "GrowthLedger — Growth Accounting & Retention",
    body: "MAU decomposed into new/retained/resurrected with quick ratio, cohort triangles in pure SQL, activation with right-censoring handled, L28 curve.",
    m: "Aha-moment users retain 45.3% vs 18.2% at week 4 · 421k events · flows sum exactly by test", repo: "product-growth-analytics" },
  { c: "ai", cat: "AI Engineering", tests: "33 tests", title: "Analytics RAG Agent",
    body: "Semantic questions → documentation RAG with citations; quantitative → guarded text-to-SQL. Guardrails enforced in code, not prompts.",
    m: "Routing 14/14 · retrieval hit@4 8/8 · hostile SQL blocked by 4-layer validation", repo: "analytics-rag-agent" },
  { c: "ai", cat: "AI Operations · FinOps", tests: "9 tests", title: "TokenLedger — LLM Cost & Quality",
    body: "OpenTelemetry GenAI tracing over 27,683 spans from my own agent: cost per successful answer, prompt-version economics, waste anomalies.",
    m: "v2 prompt: +6.5pp quality at 1.35× cost · retry storm caught at failure z=5.3 while cost z=0.5", repo: "llm-ops-analytics" },
  { c: "ai", cat: "NLP · LLM Pipeline", tests: "13 tests", title: "Review Intelligence Pipeline",
    body: "LLM aspect-sentiment extraction under a strict output contract: validation, single repair retry, hard budget caps, idempotent re-runs.",
    m: "400/400 extractions validated · $0 offline demo mode · budget guard aborts at the cap by test", repo: "review-nlp-pipeline" },
  { c: "data-eng", cat: "Modern Data Stack", tests: "26 source tests", title: "Olist Analytics Platform",
    body: "dbt Core + Snowflake: Kimball star schema with SCD2 snapshots, incremental marts with 30-day lookback, CI on ephemeral schemas.",
    m: "100k-order dataset · window-function CLV marts · zero broken deploys across PRs", repo: "dbt-snowflake-ecommerce" },
  { c: "data-eng", cat: "BigQuery · dbt · Gemini", tests: "10 tests", title: "GA Analytics Platform",
    body: "GA's nested schema flattened exactly once (double UNNEST), session-counted funnel marts, and Gemini NL-to-SQL with dry-run cost gates.",
    m: "Marts-only allowlist blocks raw-shard scans · 200MB dry-run cap before any query executes", repo: "ga-bigquery-analytics" },
  { c: "data-eng", cat: "Streaming · GCP", tests: "7 tests", title: "Real-time Streaming Pipeline",
    body: "Pub/Sub → micro-batched BigQuery with flow control, ack-after-insert, two dedup layers, and planted late events for event-time honesty.",
    m: "Pipeline latency (p50/p95) is a first-class dashboard metric · at-least-once handled honestly", repo: "gcp-streaming-pipeline" },
  { c: "stats", pc: "v", cat: "Forecasting · MLOps", tests: "9 tests", title: "Demand Forecasting + Serving",
    body: "Rolling-origin backtesting (19 folds) on a real public benchmark, FastAPI serving tested in-process, Cloud Run deployment.",
    m: "ETS 9.92% sMAPE vs seasonal-naive 10.23% — the champion barely wins, and that IS the lesson", repo: "vertex-forecasting" },
  { c: "biz", pc: "gold", cat: "Insurance · Risk", tests: "8 tests", title: "LossLens — Fraud Triage & Loss Analytics",
    body: "Synthetic P&C book with six planted fraud rings: rules + graph + anomaly + note signals combined and ablated, plus loss triangles.",
    m: "Precision@50 = 100% vs 9.8% random baseline · notes add the most signal (the LLM-triage case)", repo: "insurance-loss-analytics" },
  { c: "biz", pc: "gold", cat: "Fintech · Risk", tests: "5 tests", title: "CreditPulse — Complaint Intelligence",
    body: "CFPB complaint analytics: emerging-topic velocity, issuer scorecards, and macro lead/lag done right — on first differences.",
    m: "Planted surge caught at 5.2× velocity · 2-month macro lag recovered at r=0.667", repo: "credit-complaint-intelligence" },
  { c: "biz", pc: "p", cat: "Marketing Science", tests: "5 tests", title: "Marketing Attribution Lab",
    body: "Five attribution models graded against planted channel truth on 60k journeys — quantifying exactly what last-click misallocates.",
    m: "Last-click over-credits paid search 2.7× · removal-effect halves the error (MAE .038 vs .098)", repo: "marketing-attribution-lab" },
  { c: "bi", cat: "Power BI · DAX", tests: "star schema", title: "Power BI / DAX Showcase",
    body: "A dataset purpose-built so advanced DAX has something to prove: same-store sales, two facts, calc groups, query-time segmentation, RLS.",
    m: "69,868-row fact · time-intelligence calc group · same-store vs naive YoY = the honest-growth story", repo: "powerbi-dax-showcase" },
  { c: "bi", cat: "Tableau · Data Story", tests: "6 story points", title: "The Great Convergence",
    body: "A six-point Tableau story on global life expectancy: LOD expressions, a reader-movable threshold, and the exception made unskippable.",
    m: "Humanity in 70+ life-expectancy countries: 1.1% (1952) → 61.4% (2007) — computed, not quoted", repo: "tableau-storytelling" },
  { c: "bi", cat: "Semantic Layer", tests: "10 tests", title: "LookML Semantic Model",
    body: "Explores, native derived tables with datagroup persistence, governed always-filters — validated by a structural CI on the lkml parser.",
    m: "10-test structural CI — the LookML repo that reviews itself", repo: "looker-lookml-ecommerce" },
  { c: "bi", cat: "Excel · Power Query", tests: "M contracts", title: "Power Query Case Study",
    body: "Six messy exports — drifting headers, three date formats, currency-as-text — cleaned entirely in M, modeled in Power Pivot.",
    m: "A day of monthly copy-paste-fix reduced to Refresh All — every defect mapped to its defeat", repo: "excel-powerquery-casestudy" },
  { c: "data-eng", cat: "SQL Depth", tests: "CI-verified", title: "SQL Puzzles Showcase",
    body: "Eight hard problems — gaps & islands, sessionization, ROWS/RANGE traps, recursive rollups, EXPLAIN optimization — asserted in CI.",
    m: "Each dataset plants the edge case that breaks the obvious first attempt · 1.54× measured win", repo: "sql-puzzles" },
];

export const checklist = [
  ["Advanced SQL", "window fns · recursive CTEs · optimization → SQL Puzzles"],
  ["Experimentation & A/B statistics", "Bayesian · sequential · peeking → A/B Framework"],
  ["Causal inference", "DiD · synthetic control · matching → Casebook"],
  ["Product & growth analytics", "growth accounting · cohorts · activation → GrowthLedger"],
  ["Data modeling & modern stack", "Kimball · SCD2 · dbt · CI/CD → Olist Platform"],
  ["Cloud & big data", "Snowflake · BigQuery · PySpark · streaming → 5 projects"],
  ["BI tool fluency", "Tableau · Power BI · LookML · Excel → 4 projects"],
  ["LLM engineering with evals", "RAG · guardrails · measured accuracy → RAG Agent"],
  ["AI operations & FinOps", "OTel GenAI tracing · cost/quality → TokenLedger"],
  ["Forecasting & backtesting", "rolling-origin · honest baselines → Forecasting"],
  ["Domain depth", "healthcare · insurance · fintech · marketing → 6 projects"],
  ["Testing & reproducibility", "190+ CI tests · seeded runs · decision docs → all repos"],
];

export const GH = "https://github.com/Raveesh-rajg";
export const LI = "https://www.linkedin.com/in/raveeshrajg/";
export const EMAIL = "raveeshraj26@gmail.com";
